# CI file
name: Build-and-Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node JS
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install NPM
        run: npm install    

      - name: Run Lint
        run: npm run lint

      # Run the tests located in package.json
      - name: Run Tests
        run: npm test

# Taken from the GitHub marketplace
# https://github.com/marketplace/actions/generate-documentation
  DocumentGen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Access the document generation from the GitHub user
      - name: Github Action genshdoc
        id: action-genshdoc
        uses: vargiuscuola/genshdoc@master
      # Print the result of the process to the console
      - name: genshdoc result
        run: echo "The result of genshdoc Action was ${{ steps.action-genshdoc.outputs.result }}"
      - name: Commit files
        # Commit the file changes to GitHub
        run: |
          echo ${{ github.ref }}
          git add .
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "CI: Automated build push" -a | exit 0
      # Push changes to a file when provided a proper access token
      - name: Push changes
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
