name: Build-and-Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Move Web Files
        run: |
          cd src
          mv index.html CI-CD-Group-Project
          mv styles.css CI-CD-Group-Project
          mv app.js CI-CD-Group-Project
        
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install NPM
        run: npm install    

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test
