name: Build-and-Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install NPM
        run: npm install    

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

  DocumentGen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Github Action genshdoc
        id: action-genshdoc
        uses: vargiuscuola/genshdoc@master
      - name: genshdoc result
        run: echo "The result of genshdoc Action was ${{ steps.action-genshdoc.outputs.result }}"
      - name: Commit files
        run: |
          echo ${{ github.ref }}
          git add .
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "CI: Automated build push" -a | exit 0
      - name: Push changes
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
          github_token: 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
